# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc07912d48f4f59559fd242f4a6b9637c6ffe70060e693854438043999bbf4e594d79ef8e70c52b2c59f4ad550dd97f948ca6c579683cfad5cf6834b4cfcd948

test:
  secret_key_base: 39c98271c278d7ed1af69b7ba662a0b760a87eab60ea2e7b4e44112487936175afb66c118a54d86b7fec28e98d8e68d85d52b27a58f4d5f701a5867881812246

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
